"""another shot at martyrology tables

Revision ID: 0309f585cb29
Revises: cb17e78c4ee8
Create Date: 2021-02-25 11:22:48.339482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0309f585cb29'
down_revision = 'cb17e78c4ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datetable_calendar_date'), 'datetable', ['calendar_date'], unique=False)
    op.create_index(op.f('ix_datetable_id'), 'datetable', ['id'], unique=False)
    op.create_table('martyrologyline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_martyrologyline_id'), 'martyrologyline', ['id'], unique=False)
    op.create_index(op.f('ix_martyrologyline_prefix'), 'martyrologyline', ['prefix'], unique=False)
    op.create_index(op.f('ix_martyrologyline_suffix'), 'martyrologyline', ['suffix'], unique=False)
    op.create_index(op.f('ix_martyrologyline_title'), 'martyrologyline', ['title'], unique=False)
    op.create_table('date_association_table',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('martyrology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['datetable.id'], ),
    sa.ForeignKeyConstraint(['martyrology_id'], ['martyrology.id'], ),
    sa.PrimaryKeyConstraint('date_id', 'martyrology_id')
    )
    op.create_table('line_association_table',
    sa.Column('martyrology_id', sa.Integer(), nullable=False),
    sa.Column('martyrologyline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['martyrology_id'], ['martyrology.id'], ),
    sa.ForeignKeyConstraint(['martyrologyline_id'], ['martyrologyline.id'], ),
    sa.PrimaryKeyConstraint('martyrology_id', 'martyrologyline_id')
    )
    op.drop_index('ix_block_id', table_name='block')
    op.drop_index('ix_block_rubrics', table_name='block')
    op.drop_index('ix_block_title', table_name='block')
    op.drop_table('block')
    op.drop_index('ix_thing_id', table_name='thing')
    op.drop_table('thing')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('thing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='thing_pkey')
    )
    op.create_index('ix_thing_id', 'thing', ['id'], unique=False)
    op.create_table('block',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rubrics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='block_pkey')
    )
    op.create_index('ix_block_title', 'block', ['title'], unique=False)
    op.create_index('ix_block_rubrics', 'block', ['rubrics'], unique=False)
    op.create_index('ix_block_id', 'block', ['id'], unique=False)
    op.drop_table('line_association_table')
    op.drop_table('date_association_table')
    op.drop_index(op.f('ix_martyrologyline_title'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_suffix'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_prefix'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_id'), table_name='martyrologyline')
    op.drop_table('martyrologyline')
    op.drop_index(op.f('ix_datetable_id'), table_name='datetable')
    op.drop_index(op.f('ix_datetable_calendar_date'), table_name='datetable')
    op.drop_table('datetable')
    # ### end Alembic commands ###
