"""
crossref.

Revision ID: 0b05efd6ab5d
Revises: 4c72ad6cf786
Create Date: 2021-03-01 19:36:59.773536
"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0b05efd6ab5d"
down_revision = "4c72ad6cf786"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("hymn_verse", "hymnverse")
    op.create_index(op.f("ix_hymnverse_id"), "hymnverse", ["id"], unique=False)
    op.create_index(
        op.f("ix_hymnverse_rubrics"), "hymnverse", ["rubrics"], unique=False
    )
    op.create_index(op.f("ix_hymnverse_title"), "hymnverse", ["title"], unique=False)
    op.add_column("hymn", sa.Column("crossref", sa.String(), nullable=True))
    op.create_index(op.f("ix_hymn_crossref"), "hymn", ["crossref"], unique=False)
    op.add_column(
        "hymn_line_association_table",
        sa.Column("hymnline_id", sa.Integer(), nullable=False),
    )
    op.add_column(
        "hymn_line_association_table",
        sa.Column("hymnverse_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "hymn_line_association_table_hymn_line_id_fkey",
        "hymn_line_association_table",
        type_="foreignkey",
    )
    op.drop_constraint(
        "hymn_line_association_table_hymn_verse_id_fkey",
        "hymn_line_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "hymn_line_association_table", "hymnline", ["hymnline_id"], ["id"]
    )
    op.create_foreign_key(
        None, "hymn_line_association_table", "hymnverse", ["hymnverse_id"], ["id"]
    )
    op.drop_column("hymn_line_association_table", "hymn_line_id")
    op.drop_column("hymn_line_association_table", "hymn_verse_id")
    op.add_column(
        "hymn_verse_association_table",
        sa.Column("hymnverse_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "hymn_verse_association_table_hymn_verse_id_fkey",
        "hymn_verse_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "hymn_verse_association_table", "hymnverse", ["hymnverse_id"], ["id"]
    )
    op.drop_column("hymn_verse_association_table", "hymn_verse_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("hymnverse", "hymn_verse")
    op.add_column(
        "hymn_verse_association_table",
        sa.Column("hymn_verse_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # op.drop_constraint(None, "hymn_verse_association_table", type_="foreignkey")
    op.create_foreign_key(
        "hymn_verse_association_table_hymn_verse_id_fkey",
        "hymn_verse_association_table",
        "hymn_verse",
        ["hymn_verse_id"],
        ["id"],
    )
    op.drop_column("hymn_verse_association_table", "hymnverse_id")
    op.add_column(
        "hymn_line_association_table",
        sa.Column("hymn_verse_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "hymn_line_association_table",
        sa.Column("hymn_line_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # op.drop_constraint(None, "hymn_line_association_table", type_="foreignkey")
    # op.drop_constraint(None, "hymn_line_association_table", type_="foreignkey")
    op.create_foreign_key(
        "hymn_line_association_table_hymn_verse_id_fkey",
        "hymn_line_association_table",
        "hymn_verse",
        ["hymn_verse_id"],
        ["id"],
    )
    op.create_foreign_key(
        "hymn_line_association_table_hymn_line_id_fkey",
        "hymn_line_association_table",
        "hymnline",
        ["hymn_line_id"],
        ["id"],
    )
    op.drop_column("hymn_line_association_table", "hymnverse_id")
    op.drop_column("hymn_line_association_table", "hymnline_id")
    op.drop_index(op.f("ix_hymn_crossref"), table_name="hymn")
    op.drop_column("hymn", "crossref")
    # op.create_index("ix_hymn_verse_title", "hymn_verse", ["title"], unique=False)
    # op.create_index("ix_hymn_verse_rubrics", "hymn_verse", ["rubrics"], unique=False)
    # op.create_index("ix_hymn_verse_id", "hymn_verse", ["id"], unique=False)
    op.drop_index(op.f("ix_hymnverse_title"), table_name="hymnverse")
    op.drop_index(op.f("ix_hymnverse_rubrics"), table_name="hymnverse")
    op.drop_index(op.f("ix_hymnverse_id"), table_name="hymnverse")
    # ### end Alembic commands ###
