"""add lang col

Revision ID: 0ce249bb40f3
Revises: bffb6ac4a17d
Create Date: 2021-02-26 17:20:36.964743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce249bb40f3'
down_revision = 'bffb6ac4a17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feast', sa.Column('language', sa.String(), nullable=True))
    op.create_index(op.f('ix_feast_language'), 'feast', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feast_language'), table_name='feast')
    op.drop_column('feast', 'language')
    # ### end Alembic commands ###
