"""prayer revision

Revision ID: 111e9c58cd75
Revises: 4437530c007d
Create Date: 2021-03-03 19:38:00.730888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111e9c58cd75'
down_revision = '4437530c007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer', sa.Column('termination_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'prayer', 'prayerline', ['termination_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prayer', type_='foreignkey')
    op.drop_column('prayer', 'termination_id')
    # ### end Alembic commands ###
