"""compline

Revision ID: 1cda72427651
Revises: f4b374f2de80
Create Date: 2021-03-19 16:58:56.117737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cda72427651'
down_revision = 'f4b374f2de80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antiphon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antiphon_content'), 'antiphon', ['content'], unique=False)
    op.create_index(op.f('ix_antiphon_id'), 'antiphon', ['id'], unique=False)
    op.create_index(op.f('ix_antiphon_prefix'), 'antiphon', ['prefix'], unique=False)
    op.create_index(op.f('ix_antiphon_rubrics'), 'antiphon', ['rubrics'], unique=False)
    op.create_index(op.f('ix_antiphon_sourcefile'), 'antiphon', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_antiphon_suffix'), 'antiphon', ['suffix'], unique=False)
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('posture', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_id'), 'reading', ['id'], unique=False)
    op.create_index(op.f('ix_reading_posture'), 'reading', ['posture'], unique=False)
    op.create_index(op.f('ix_reading_ref'), 'reading', ['ref'], unique=False)
    op.create_index(op.f('ix_reading_rubrics'), 'reading', ['rubrics'], unique=False)
    op.create_index(op.f('ix_reading_sourcefile'), 'reading', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_reading_title'), 'reading', ['title'], unique=False)
    op.create_table('rubric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubric_content'), 'rubric', ['content'], unique=False)
    op.create_index(op.f('ix_rubric_id'), 'rubric', ['id'], unique=False)
    op.create_index(op.f('ix_rubric_prefix'), 'rubric', ['prefix'], unique=False)
    op.create_index(op.f('ix_rubric_rubrics'), 'rubric', ['rubrics'], unique=False)
    op.create_index(op.f('ix_rubric_sourcefile'), 'rubric', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_rubric_suffix'), 'rubric', ['suffix'], unique=False)
    op.create_table('versicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('posture', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versicle_id'), 'versicle', ['id'], unique=False)
    op.create_index(op.f('ix_versicle_posture'), 'versicle', ['posture'], unique=False)
    op.create_index(op.f('ix_versicle_rubrics'), 'versicle', ['rubrics'], unique=False)
    op.create_index(op.f('ix_versicle_sourcefile'), 'versicle', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_versicle_title'), 'versicle', ['title'], unique=False)
    op.create_table('reading_line_association_table',
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ),
    sa.PrimaryKeyConstraint('reading_id', 'line_id')
    )
    op.create_table('versicle_line_association_table',
    sa.Column('versicle_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.ForeignKeyConstraint(['versicle_id'], ['versicle.id'], ),
    sa.PrimaryKeyConstraint('versicle_id', 'line_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('versicle_line_association_table')
    op.drop_table('reading_line_association_table')
    op.drop_index(op.f('ix_versicle_title'), table_name='versicle')
    op.drop_index(op.f('ix_versicle_sourcefile'), table_name='versicle')
    op.drop_index(op.f('ix_versicle_rubrics'), table_name='versicle')
    op.drop_index(op.f('ix_versicle_posture'), table_name='versicle')
    op.drop_index(op.f('ix_versicle_id'), table_name='versicle')
    op.drop_table('versicle')
    op.drop_index(op.f('ix_rubric_suffix'), table_name='rubric')
    op.drop_index(op.f('ix_rubric_sourcefile'), table_name='rubric')
    op.drop_index(op.f('ix_rubric_rubrics'), table_name='rubric')
    op.drop_index(op.f('ix_rubric_prefix'), table_name='rubric')
    op.drop_index(op.f('ix_rubric_id'), table_name='rubric')
    op.drop_index(op.f('ix_rubric_content'), table_name='rubric')
    op.drop_table('rubric')
    op.drop_index(op.f('ix_reading_title'), table_name='reading')
    op.drop_index(op.f('ix_reading_sourcefile'), table_name='reading')
    op.drop_index(op.f('ix_reading_rubrics'), table_name='reading')
    op.drop_index(op.f('ix_reading_ref'), table_name='reading')
    op.drop_index(op.f('ix_reading_posture'), table_name='reading')
    op.drop_index(op.f('ix_reading_id'), table_name='reading')
    op.drop_table('reading')
    op.drop_index(op.f('ix_antiphon_suffix'), table_name='antiphon')
    op.drop_index(op.f('ix_antiphon_sourcefile'), table_name='antiphon')
    op.drop_index(op.f('ix_antiphon_rubrics'), table_name='antiphon')
    op.drop_index(op.f('ix_antiphon_prefix'), table_name='antiphon')
    op.drop_index(op.f('ix_antiphon_id'), table_name='antiphon')
    op.drop_index(op.f('ix_antiphon_content'), table_name='antiphon')
    op.drop_table('antiphon')
    # ### end Alembic commands ###
