"""add version col

Revision ID: 2a6db7cd5566
Revises: 2acfe6b3710b
Create Date: 2021-02-26 12:48:05.984446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6db7cd5566'
down_revision = '2acfe6b3710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commemoration', sa.Column('version', sa.String(), nullable=True))
    op.create_index(op.f('ix_commemoration_version'), 'commemoration', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commemoration_version'), table_name='commemoration')
    op.drop_column('commemoration', 'version')
    # ### end Alembic commands ###
