"""add calendar tables

Revision ID: 2acfe6b3710b
Revises: 7e5af21373ef
Create Date: 2021-02-26 12:34:59.872669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2acfe6b3710b'
down_revision = '7e5af21373ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commemoration',
    sa.Column('rank_name', sa.String(), nullable=True),
    sa.Column('rank_defeatable', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commemoration_id'), 'commemoration', ['id'], unique=False)
    op.create_index(op.f('ix_commemoration_name'), 'commemoration', ['name'], unique=False)
    op.create_index(op.f('ix_commemoration_rank_name'), 'commemoration', ['rank_name'], unique=False)
    op.create_table('feast',
    sa.Column('rank_name', sa.String(), nullable=True),
    sa.Column('rank_defeatable', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type_', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('octave', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feast_id'), 'feast', ['id'], unique=False)
    op.create_index(op.f('ix_feast_name'), 'feast', ['name'], unique=False)
    op.create_index(op.f('ix_feast_octave'), 'feast', ['octave'], unique=False)
    op.create_index(op.f('ix_feast_rank_name'), 'feast', ['rank_name'], unique=False)
    op.create_index(op.f('ix_feast_type_'), 'feast', ['type_'], unique=False)
    op.create_index(op.f('ix_feast_version'), 'feast', ['version'], unique=False)
    op.create_table('commemoration_association_table',
    sa.Column('feast_id', sa.Integer(), nullable=False),
    sa.Column('commemoration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commemoration_id'], ['commemoration.id'], ),
    sa.ForeignKeyConstraint(['feast_id'], ['feast.id'], ),
    sa.PrimaryKeyConstraint('feast_id', 'commemoration_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commemoration_association_table')
    op.drop_index(op.f('ix_feast_version'), table_name='feast')
    op.drop_index(op.f('ix_feast_type_'), table_name='feast')
    op.drop_index(op.f('ix_feast_rank_name'), table_name='feast')
    op.drop_index(op.f('ix_feast_octave'), table_name='feast')
    op.drop_index(op.f('ix_feast_name'), table_name='feast')
    op.drop_index(op.f('ix_feast_id'), table_name='feast')
    op.drop_table('feast')
    op.drop_index(op.f('ix_commemoration_rank_name'), table_name='commemoration')
    op.drop_index(op.f('ix_commemoration_name'), table_name='commemoration')
    op.drop_index(op.f('ix_commemoration_id'), table_name='commemoration')
    op.drop_table('commemoration')
    # ### end Alembic commands ###
