"""start again

Revision ID: 32774f603c7a
Revises: 
Create Date: 2021-02-25 15:34:25.244505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32774f603c7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datetable_calendar_date'), 'datetable', ['calendar_date'], unique=False)
    op.create_index(op.f('ix_datetable_id'), 'datetable', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_description'), 'item', ['description'], unique=False)
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    op.create_index(op.f('ix_item_title'), 'item', ['title'], unique=False)
    op.create_table('martyrologyline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_martyrologyline_id'), 'martyrologyline', ['id'], unique=False)
    op.create_index(op.f('ix_martyrologyline_prefix'), 'martyrologyline', ['prefix'], unique=False)
    op.create_index(op.f('ix_martyrologyline_suffix'), 'martyrologyline', ['suffix'], unique=False)
    op.create_index(op.f('ix_martyrologyline_title'), 'martyrologyline', ['title'], unique=False)
    op.create_table('ordinals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.PickleType(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordinals_id'), 'ordinals', ['id'], unique=False)
    op.create_table('olddatetemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('ordinals_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ordinals_id'], ['ordinals.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_olddatetemplate_id'), 'olddatetemplate', ['id'], unique=False)
    op.create_index(op.f('ix_olddatetemplate_language'), 'olddatetemplate', ['language'], unique=False)
    op.create_table('martyrology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('datestr', sa.String(), nullable=True),
    sa.Column('old_date_template_id', sa.Integer(), nullable=True),
    sa.Column('julian_date', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['old_date_template_id'], ['olddatetemplate.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_martyrology_datestr'), 'martyrology', ['datestr'], unique=False)
    op.create_index(op.f('ix_martyrology_id'), 'martyrology', ['id'], unique=False)
    op.create_index(op.f('ix_martyrology_title'), 'martyrology', ['title'], unique=False)
    op.create_table('date_association_table',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('martyrology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['datetable.id'], ),
    sa.ForeignKeyConstraint(['martyrology_id'], ['martyrology.id'], ),
    sa.PrimaryKeyConstraint('date_id', 'martyrology_id')
    )
    op.create_table('line_association_table',
    sa.Column('martyrology_id', sa.Integer(), nullable=False),
    sa.Column('martyrologyline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['martyrology_id'], ['martyrology.id'], ),
    sa.ForeignKeyConstraint(['martyrologyline_id'], ['martyrologyline.id'], ),
    sa.PrimaryKeyConstraint('martyrology_id', 'martyrologyline_id')
    )
    op.create_table('verse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('verse', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verse_id'), 'verse', ['id'], unique=False)
    op.create_index(op.f('ix_verse_rubrics'), 'verse', ['rubrics'], unique=False)
    op.create_index(op.f('ix_verse_title'), 'verse', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verse_title'), table_name='verse')
    op.drop_index(op.f('ix_verse_rubrics'), table_name='verse')
    op.drop_index(op.f('ix_verse_id'), table_name='verse')
    op.drop_table('verse')
    op.drop_table('line_association_table')
    op.drop_table('date_association_table')
    op.drop_index(op.f('ix_martyrology_title'), table_name='martyrology')
    op.drop_index(op.f('ix_martyrology_id'), table_name='martyrology')
    op.drop_index(op.f('ix_martyrology_datestr'), table_name='martyrology')
    op.drop_table('martyrology')
    op.drop_index(op.f('ix_olddatetemplate_language'), table_name='olddatetemplate')
    op.drop_index(op.f('ix_olddatetemplate_id'), table_name='olddatetemplate')
    op.drop_table('olddatetemplate')
    op.drop_index(op.f('ix_ordinals_id'), table_name='ordinals')
    op.drop_table('ordinals')
    op.drop_index(op.f('ix_martyrologyline_title'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_suffix'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_prefix'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_id'), table_name='martyrologyline')
    op.drop_table('martyrologyline')
    op.drop_index(op.f('ix_item_title'), table_name='item')
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_description'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_datetable_id'), table_name='datetable')
    op.drop_index(op.f('ix_datetable_calendar_date'), table_name='datetable')
    op.drop_table('datetable')
    # ### end Alembic commands ###
