"""add version and lang

Revision ID: 4c72ad6cf786
Revises: a7b77e505950
Create Date: 2021-03-01 14:19:14.601341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c72ad6cf786'
down_revision = 'a7b77e505950'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
