"""update verse again

Revision ID: 4d8a0de0447c
Revises: 54a2b293ba6e
Create Date: 2021-02-25 15:41:41.744713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8a0de0447c'
down_revision = '54a2b293ba6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse', sa.Column('book', sa.String(), nullable=True))
    op.create_index(op.f('ix_verse_book'), 'verse', ['book'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verse_book'), table_name='verse')
    op.drop_column('verse', 'book')
    # ### end Alembic commands ###
