"""update verse

Revision ID: 54a2b293ba6e
Revises: 32774f603c7a
Create Date: 2021-02-25 15:40:26.314499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a2b293ba6e'
down_revision = '32774f603c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse', sa.Column('version', sa.String(), nullable=True))
    op.create_index(op.f('ix_verse_language'), 'verse', ['language'], unique=False)
    op.create_index(op.f('ix_verse_version'), 'verse', ['version'], unique=False)
    op.drop_column('verse', 'verse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse', sa.Column('verse', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_verse_version'), table_name='verse')
    op.drop_index(op.f('ix_verse_language'), table_name='verse')
    op.drop_column('verse', 'version')
    # ### end Alembic commands ###
