"""use mixins

Revision ID: 5c124fadc268
Revises: 5d74b4a74001
Create Date: 2021-03-01 14:09:30.291696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c124fadc268'
down_revision = '5d74b4a74001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_martyrology_rubrics'), 'martyrology', ['rubrics'], unique=False)
    op.create_index(op.f('ix_martyrologyline_content'), 'martyrologyline', ['content'], unique=False)
    op.create_index(op.f('ix_martyrologyline_rubrics'), 'martyrologyline', ['rubrics'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_martyrologyline_rubrics'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrologyline_content'), table_name='martyrologyline')
    op.drop_index(op.f('ix_martyrology_rubrics'), table_name='martyrology')
    # ### end Alembic commands ###
