"""add datestr col!

Revision ID: 5d74b4a74001
Revises: 0ce249bb40f3
Create Date: 2021-02-26 18:14:15.952307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d74b4a74001'
down_revision = '0ce249bb40f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feast', sa.Column('datestr', sa.String(), nullable=True))
    op.create_index(op.f('ix_feast_datestr'), 'feast', ['datestr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feast_datestr'), table_name='feast')
    op.drop_column('feast', 'datestr')
    # ### end Alembic commands ###
