"""add ordering col

Revision ID: 60a7d8b56fbe
Revises: c9d2cfda23c9
Create Date: 2021-03-02 18:51:55.065417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a7d8b56fbe'
down_revision = 'c9d2cfda23c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hymnverse', sa.Column('verseno', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hymnverse', 'verseno')
    # ### end Alembic commands ###
