"""add do mixin cols

Revision ID: 6e9d64cbb619
Revises: 60a7d8b56fbe
Create Date: 2021-03-03 12:00:10.596206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9d64cbb619'
down_revision = '60a7d8b56fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commemoration', sa.Column('at', sa.String(), nullable=True))
    op.add_column('commemoration', sa.Column('sourcefile', sa.String(), nullable=True))
    op.create_index(op.f('ix_commemoration_at'), 'commemoration', ['at'], unique=False)
    op.create_index(op.f('ix_commemoration_sourcefile'), 'commemoration', ['sourcefile'], unique=False)
    op.add_column('feast', sa.Column('at', sa.String(), nullable=True))
    op.add_column('feast', sa.Column('sourcefile', sa.String(), nullable=True))
    op.create_index(op.f('ix_feast_at'), 'feast', ['at'], unique=False)
    op.create_index(op.f('ix_feast_sourcefile'), 'feast', ['sourcefile'], unique=False)
    op.add_column('hymn', sa.Column('at', sa.String(), nullable=True))
    op.add_column('hymn', sa.Column('sourcefile', sa.String(), nullable=True))
    op.create_index(op.f('ix_hymn_at'), 'hymn', ['at'], unique=False)
    op.create_index(op.f('ix_hymn_sourcefile'), 'hymn', ['sourcefile'], unique=False)
    op.add_column('martyrology', sa.Column('at', sa.String(), nullable=True))
    op.add_column('martyrology', sa.Column('sourcefile', sa.String(), nullable=True))
    op.create_index(op.f('ix_martyrology_at'), 'martyrology', ['at'], unique=False)
    op.create_index(op.f('ix_martyrology_sourcefile'), 'martyrology', ['sourcefile'], unique=False)
    op.add_column('verse', sa.Column('at', sa.String(), nullable=True))
    op.add_column('verse', sa.Column('sourcefile', sa.String(), nullable=True))
    op.create_index(op.f('ix_verse_at'), 'verse', ['at'], unique=False)
    op.create_index(op.f('ix_verse_sourcefile'), 'verse', ['sourcefile'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verse_sourcefile'), table_name='verse')
    op.drop_index(op.f('ix_verse_at'), table_name='verse')
    op.drop_column('verse', 'sourcefile')
    op.drop_column('verse', 'at')
    op.drop_index(op.f('ix_martyrology_sourcefile'), table_name='martyrology')
    op.drop_index(op.f('ix_martyrology_at'), table_name='martyrology')
    op.drop_column('martyrology', 'sourcefile')
    op.drop_column('martyrology', 'at')
    op.drop_index(op.f('ix_hymn_sourcefile'), table_name='hymn')
    op.drop_index(op.f('ix_hymn_at'), table_name='hymn')
    op.drop_column('hymn', 'sourcefile')
    op.drop_column('hymn', 'at')
    op.drop_index(op.f('ix_feast_sourcefile'), table_name='feast')
    op.drop_index(op.f('ix_feast_at'), table_name='feast')
    op.drop_column('feast', 'sourcefile')
    op.drop_column('feast', 'at')
    op.drop_index(op.f('ix_commemoration_sourcefile'), table_name='commemoration')
    op.drop_index(op.f('ix_commemoration_at'), table_name='commemoration')
    op.drop_column('commemoration', 'sourcefile')
    op.drop_column('commemoration', 'at')
    # ### end Alembic commands ###
