"""
single_table.

Revision ID: 7c7c120a47e9
Revises: 1cda72427651
Create Date: 2021-03-23 16:21:45.974379
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app

# revision identifiers, used by Alembic.
revision = "7c7c120a47e9"
down_revision = "1cda72427651"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "officething",
        sa.Column("sourcefile", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discriminator", sa.String(), nullable=True),
        sa.Column("rubrics", sa.String(), nullable=True),
        sa.Column("posture", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("versions", app.models.office.JSONEncoded(), nullable=True),
        sa.Column("prefix", sa.String(), nullable=True),
        sa.Column("suffix", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("book", sa.String(), nullable=True),
        sa.Column("aka", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("ref", sa.String(), nullable=True),
        sa.Column("verseno", sa.Integer(), nullable=True),
        sa.Column("type_", sa.String(), nullable=True),
        sa.Column("termination_id", sa.Integer(), nullable=True),
        sa.Column("at", app.models.office.JSONEncoded(), nullable=True),
        sa.Column("datestr", sa.String(), nullable=True),
        sa.Column("old_date_template_id", sa.Integer(), nullable=True),
        sa.Column("julian_date", sa.String(), nullable=True),
        sa.Column("read_first", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["old_date_template_id"], ["olddatetemplate.id"],),
        sa.ForeignKeyConstraint(["termination_id"], ["officething.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_officething_aka"), "officething", ["aka"], unique=False)
    op.create_index(op.f("ix_officething_book"), "officething", ["book"], unique=False)
    op.create_index(
        op.f("ix_officething_content"), "officething", ["content"], unique=False
    )
    op.create_index(
        op.f("ix_officething_datestr"), "officething", ["datestr"], unique=False
    )
    op.create_index(
        op.f("ix_officething_language"), "officething", ["language"], unique=False
    )
    op.create_index(
        op.f("ix_officething_posture"), "officething", ["posture"], unique=False
    )
    op.create_index(
        op.f("ix_officething_prefix"), "officething", ["prefix"], unique=False
    )
    op.create_index(op.f("ix_officething_ref"), "officething", ["ref"], unique=False)
    op.create_index(
        op.f("ix_officething_rubrics"), "officething", ["rubrics"], unique=False
    )
    op.create_index(
        op.f("ix_officething_sourcefile"), "officething", ["sourcefile"], unique=False
    )
    op.create_index(
        op.f("ix_officething_suffix"), "officething", ["suffix"], unique=False
    )
    op.create_index(
        op.f("ix_officething_title"), "officething", ["title"], unique=False
    )
    op.create_index(
        op.f("ix_officething_type_"), "officething", ["type_"], unique=False
    )
    op.create_index(
        op.f("ix_officething_version"), "officething", ["version"], unique=False
    )
    op.create_table(
        "hymnassoc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["officething.id"],),
        sa.ForeignKeyConstraint(["parent_id"], ["officething.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hymnverseassoc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["officething.id"],),
        sa.ForeignKeyConstraint(["parent_id"], ["officething.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "officeassoc",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["officething.id"],),
        sa.ForeignKeyConstraint(["parent_id"], ["officething.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_versicle_id", table_name="versicle")
    op.drop_index("ix_versicle_posture", table_name="versicle")
    op.drop_index("ix_versicle_rubrics", table_name="versicle")
    op.drop_index("ix_versicle_sourcefile", table_name="versicle")
    op.drop_index("ix_versicle_title", table_name="versicle")
    op.drop_table("versicle_line_association_table")
    op.drop_table("versicle")
    op.drop_index("ix_bibleverse_aka", table_name="bibleverse")
    op.drop_index("ix_bibleverse_book", table_name="bibleverse")
    op.drop_index("ix_bibleverse_content", table_name="bibleverse")
    op.drop_index("ix_bibleverse_id", table_name="bibleverse")
    op.drop_index("ix_bibleverse_language", table_name="bibleverse")
    op.drop_index("ix_bibleverse_prefix", table_name="bibleverse")
    op.drop_index("ix_bibleverse_rubrics", table_name="bibleverse")
    op.drop_index("ix_bibleverse_sourcefile", table_name="bibleverse")
    op.drop_index("ix_bibleverse_suffix", table_name="bibleverse")
    op.drop_index("ix_bibleverse_version", table_name="bibleverse")
    op.drop_table("bibleverse")
    op.drop_table("hymn_line_association_table")
    op.drop_index("ix_line_content", table_name="line")
    op.drop_index("ix_line_id", table_name="line")
    op.drop_index("ix_line_prefix", table_name="line")
    op.drop_index("ix_line_rubrics", table_name="line")
    op.drop_index("ix_line_sourcefile", table_name="line")
    op.drop_index("ix_line_suffix", table_name="line")
    op.drop_table("hymn_verse_association_table")
    op.drop_index("ix_prayerline_content", table_name="prayerline")
    op.drop_index("ix_prayerline_id", table_name="prayerline")
    op.drop_index("ix_prayerline_prefix", table_name="prayerline")
    op.drop_index("ix_prayerline_rubrics", table_name="prayerline")
    op.drop_index("ix_prayerline_suffix", table_name="prayerline")
    op.drop_table("line_association_table")
    op.drop_index("ix_reading_id", table_name="reading")
    op.drop_index("ix_reading_posture", table_name="reading")
    op.drop_index("ix_reading_ref", table_name="reading")
    op.drop_index("ix_reading_rubrics", table_name="reading")
    op.drop_index("ix_reading_sourcefile", table_name="reading")
    op.drop_index("ix_reading_title", table_name="reading")
    op.drop_table("reading_line_association_table")
    op.drop_table("reading")
    op.drop_index("ix_hymnline_content", table_name="hymnline")
    op.drop_index("ix_hymnline_id", table_name="hymnline")
    op.drop_index("ix_hymnline_prefix", table_name="hymnline")
    op.drop_index("ix_hymnline_rubrics", table_name="hymnline")
    op.drop_index("ix_hymnline_suffix", table_name="hymnline")
    op.drop_table("hymnline")
    op.drop_index("ix_antiphon_content", table_name="antiphon")
    op.drop_index("ix_antiphon_id", table_name="antiphon")
    op.drop_index("ix_antiphon_prefix", table_name="antiphon")
    op.drop_index("ix_antiphon_rubrics", table_name="antiphon")
    op.drop_index("ix_antiphon_sourcefile", table_name="antiphon")
    op.drop_index("ix_antiphon_suffix", table_name="antiphon")
    op.drop_table("antiphon")
    op.drop_index("ix_hymnverse_id", table_name="hymnverse")
    op.drop_index("ix_hymnverse_posture", table_name="hymnverse")
    op.drop_index("ix_hymnverse_rubrics", table_name="hymnverse")
    op.drop_index("ix_hymnverse_title", table_name="hymnverse")
    op.drop_table("hymnverse")
    op.drop_index("ix_hymn_crossref", table_name="hymn")
    op.drop_index("ix_hymn_id", table_name="hymn")
    op.drop_index("ix_hymn_language", table_name="hymn")
    op.drop_index("ix_hymn_posture", table_name="hymn")
    op.drop_index("ix_hymn_rubrics", table_name="hymn")
    op.drop_index("ix_hymn_sourcefile", table_name="hymn")
    op.drop_index("ix_hymn_title", table_name="hymn")
    op.drop_index("ix_hymn_type_", table_name="hymn")
    op.drop_index("ix_hymn_version", table_name="hymn")
    op.drop_table("hymn")
    op.drop_index("ix_martyrologyline_content", table_name="martyrologyline")
    op.drop_index("ix_martyrologyline_id", table_name="martyrologyline")
    op.drop_index("ix_martyrologyline_prefix", table_name="martyrologyline")
    op.drop_index("ix_martyrologyline_rubrics", table_name="martyrologyline")
    op.drop_index("ix_martyrologyline_suffix", table_name="martyrologyline")
    op.drop_index("ix_martyrologyline_title", table_name="martyrologyline")
    op.drop_table("martyrologyline")
    op.drop_table("prayer_line_association_table")
    op.drop_index("ix_prayer_crossref", table_name="prayer")
    op.drop_index("ix_prayer_id", table_name="prayer")
    op.drop_index("ix_prayer_language", table_name="prayer")
    op.drop_index("ix_prayer_posture", table_name="prayer")
    op.drop_index("ix_prayer_rubrics", table_name="prayer")
    op.drop_index("ix_prayer_title", table_name="prayer")
    op.drop_index("ix_prayer_type_", table_name="prayer")
    op.drop_index("ix_prayer_version", table_name="prayer")
    op.drop_table("prayer")
    op.drop_index("ix_block_id", table_name="block")
    op.drop_index("ix_block_posture", table_name="block")
    op.drop_index("ix_block_rubrics", table_name="block")
    op.drop_index("ix_block_sourcefile", table_name="block")
    op.drop_index("ix_block_title", table_name="block")
    op.drop_index("ix_martyrology_datestr", table_name="martyrology")
    op.drop_index("ix_martyrology_id", table_name="martyrology")
    op.drop_index("ix_martyrology_posture", table_name="martyrology")
    op.drop_index("ix_martyrology_rubrics", table_name="martyrology")
    op.drop_index("ix_martyrology_sourcefile", table_name="martyrology")
    op.drop_index("ix_martyrology_title", table_name="martyrology")
    op.drop_index("ix_rubric_content", table_name="rubric")
    op.drop_index("ix_rubric_id", table_name="rubric")
    op.drop_index("ix_rubric_prefix", table_name="rubric")
    op.drop_index("ix_rubric_rubrics", table_name="rubric")
    op.drop_index("ix_rubric_sourcefile", table_name="rubric")
    op.drop_index("ix_rubric_suffix", table_name="rubric")
    op.drop_table("rubric")
    op.drop_table("block_line_association_table")
    op.drop_table("prayerline")
    op.drop_table("line")
    op.drop_table("block")

    op.drop_constraint(
        "date_association_table_martyrology_id_fkey",
        "date_association_table",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "date_association_table", "officething", ["martyrology_id"], ["id"]
    )
    op.alter_column(
        "ordinals",
        "content",
        existing_type=postgresql.BYTEA(),
        type_=app.models.office.JSONEncoded(),
        existing_nullable=True,
    )
    op.drop_table("martyrology")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ordinals",
        "content",
        existing_type=app.models.office.JSONEncoded(),
        type_=postgresql.BYTEA(),
        existing_nullable=True,
    )
    op.drop_constraint(None, "date_association_table", type_="foreignkey")
    op.create_foreign_key(
        "date_association_table_martyrology_id_fkey",
        "date_association_table",
        "martyrology",
        ["martyrology_id"],
        ["id"],
    )
    op.create_table(
        "block_line_association_table",
        sa.Column("block_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("line_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["block.id"],
            name="block_line_association_table_block_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["line_id"], ["line.id"], name="block_line_association_table_line_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "block_id", "line_id", name="block_line_association_table_pkey"
        ),
    )
    op.create_table(
        "rubric",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="rubric_owner_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="rubric_pkey"),
    )
    op.create_index("ix_rubric_suffix", "rubric", ["suffix"], unique=False)
    op.create_index("ix_rubric_sourcefile", "rubric", ["sourcefile"], unique=False)
    op.create_index("ix_rubric_rubrics", "rubric", ["rubrics"], unique=False)
    op.create_index("ix_rubric_prefix", "rubric", ["prefix"], unique=False)
    op.create_index("ix_rubric_id", "rubric", ["id"], unique=False)
    op.create_index("ix_rubric_content", "rubric", ["content"], unique=False)
    op.create_table(
        "martyrology",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('martyrology_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("datestr", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "old_date_template_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("julian_date", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("read_first", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["old_date_template_id"],
            ["olddatetemplate.id"],
            name="martyrology_old_date_template_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="martyrology_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="martyrology_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_martyrology_title", "martyrology", ["title"], unique=False)
    op.create_index(
        "ix_martyrology_sourcefile", "martyrology", ["sourcefile"], unique=False
    )
    op.create_index("ix_martyrology_rubrics", "martyrology", ["rubrics"], unique=False)
    op.create_index("ix_martyrology_posture", "martyrology", ["posture"], unique=False)
    op.create_index("ix_martyrology_id", "martyrology", ["id"], unique=False)
    op.create_index("ix_martyrology_datestr", "martyrology", ["datestr"], unique=False)
    op.create_table(
        "block",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="block_owner_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="block_pkey"),
    )
    op.create_index("ix_block_title", "block", ["title"], unique=False)
    op.create_index("ix_block_sourcefile", "block", ["sourcefile"], unique=False)
    op.create_index("ix_block_rubrics", "block", ["rubrics"], unique=False)
    op.create_index("ix_block_posture", "block", ["posture"], unique=False)
    op.create_index("ix_block_id", "block", ["id"], unique=False)
    op.create_table(
        "prayer",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('prayer_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("crossref", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("type_", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("at", postgresql.BYTEA(), autoincrement=False, nullable=True),
        sa.Column("termination_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="prayer_owner_id_fkey"),
        sa.ForeignKeyConstraint(
            ["termination_id"], ["prayerline.id"], name="prayer_termination_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="prayer_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_prayer_version", "prayer", ["version"], unique=False)
    op.create_index("ix_prayer_type_", "prayer", ["type_"], unique=False)
    op.create_index("ix_prayer_title", "prayer", ["title"], unique=False)
    op.create_index("ix_prayer_rubrics", "prayer", ["rubrics"], unique=False)
    op.create_index("ix_prayer_posture", "prayer", ["posture"], unique=False)
    op.create_index("ix_prayer_language", "prayer", ["language"], unique=False)
    op.create_index("ix_prayer_id", "prayer", ["id"], unique=False)
    op.create_index("ix_prayer_crossref", "prayer", ["crossref"], unique=False)
    op.create_table(
        "prayer_line_association_table",
        sa.Column("prayerline_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("prayer_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["prayer_id"],
            ["prayer.id"],
            name="prayer_line_association_table_prayer_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["prayerline_id"],
            ["prayerline.id"],
            name="prayer_line_association_table_prayerline_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "prayerline_id", "prayer_id", name="prayer_line_association_table_pkey"
        ),
    )
    op.create_table(
        "martyrologyline",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('martyrologyline_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="martyrologyline_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="martyrologyline_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        "ix_martyrologyline_title", "martyrologyline", ["title"], unique=False
    )
    op.create_index(
        "ix_martyrologyline_suffix", "martyrologyline", ["suffix"], unique=False
    )
    op.create_index(
        "ix_martyrologyline_rubrics", "martyrologyline", ["rubrics"], unique=False
    )
    op.create_index(
        "ix_martyrologyline_prefix", "martyrologyline", ["prefix"], unique=False
    )
    op.create_index("ix_martyrologyline_id", "martyrologyline", ["id"], unique=False)
    op.create_index(
        "ix_martyrologyline_content", "martyrologyline", ["content"], unique=False
    )
    op.create_table(
        "hymn",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('hymn_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("crossref", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("type_", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="hymn_owner_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="hymn_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_hymn_version", "hymn", ["version"], unique=False)
    op.create_index("ix_hymn_type_", "hymn", ["type_"], unique=False)
    op.create_index("ix_hymn_title", "hymn", ["title"], unique=False)
    op.create_index("ix_hymn_sourcefile", "hymn", ["sourcefile"], unique=False)
    op.create_index("ix_hymn_rubrics", "hymn", ["rubrics"], unique=False)
    op.create_index("ix_hymn_posture", "hymn", ["posture"], unique=False)
    op.create_index("ix_hymn_language", "hymn", ["language"], unique=False)
    op.create_index("ix_hymn_id", "hymn", ["id"], unique=False)
    op.create_index("ix_hymn_crossref", "hymn", ["crossref"], unique=False)
    op.create_table(
        "hymnverse",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('hymn_verse_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("verseno", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="hymn_verse_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="hymn_verse_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_hymnverse_title", "hymnverse", ["title"], unique=False)
    op.create_index("ix_hymnverse_rubrics", "hymnverse", ["rubrics"], unique=False)
    op.create_index("ix_hymnverse_posture", "hymnverse", ["posture"], unique=False)
    op.create_index("ix_hymnverse_id", "hymnverse", ["id"], unique=False)
    op.create_table(
        "reading_line_association_table",
        sa.Column("reading_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("line_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"], ["line.id"], name="reading_line_association_table_line_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["reading_id"],
            ["reading.id"],
            name="reading_line_association_table_reading_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "reading_id", "line_id", name="reading_line_association_table_pkey"
        ),
    )
    op.create_table(
        "antiphon",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="antiphon_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="antiphon_pkey"),
    )
    op.create_index("ix_antiphon_suffix", "antiphon", ["suffix"], unique=False)
    op.create_index("ix_antiphon_sourcefile", "antiphon", ["sourcefile"], unique=False)
    op.create_index("ix_antiphon_rubrics", "antiphon", ["rubrics"], unique=False)
    op.create_index("ix_antiphon_prefix", "antiphon", ["prefix"], unique=False)
    op.create_index("ix_antiphon_id", "antiphon", ["id"], unique=False)
    op.create_index("ix_antiphon_content", "antiphon", ["content"], unique=False)
    op.create_table(
        "hymnline",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('hymnline_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="hymnline_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="hymnline_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_hymnline_suffix", "hymnline", ["suffix"], unique=False)
    op.create_index("ix_hymnline_rubrics", "hymnline", ["rubrics"], unique=False)
    op.create_index("ix_hymnline_prefix", "hymnline", ["prefix"], unique=False)
    op.create_index("ix_hymnline_id", "hymnline", ["id"], unique=False)
    op.create_index("ix_hymnline_content", "hymnline", ["content"], unique=False)
    op.create_table(
        "reading",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("ref", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="reading_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="reading_pkey"),
    )
    op.create_index("ix_reading_title", "reading", ["title"], unique=False)
    op.create_index("ix_reading_sourcefile", "reading", ["sourcefile"], unique=False)
    op.create_index("ix_reading_rubrics", "reading", ["rubrics"], unique=False)
    op.create_index("ix_reading_ref", "reading", ["ref"], unique=False)
    op.create_index("ix_reading_posture", "reading", ["posture"], unique=False)
    op.create_index("ix_reading_id", "reading", ["id"], unique=False)
    op.create_table(
        "versicle_line_association_table",
        sa.Column("versicle_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("line_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["line_id"],
            ["line.id"],
            name="versicle_line_association_table_line_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["versicle_id"],
            ["versicle.id"],
            name="versicle_line_association_table_versicle_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "versicle_id", "line_id", name="versicle_line_association_table_pkey"
        ),
    )
    op.create_table(
        "line_association_table",
        sa.Column("martyrology_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "martyrologyline_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["martyrology_id"],
            ["martyrology.id"],
            name="line_association_table_martyrology_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["martyrologyline_id"],
            ["martyrologyline.id"],
            name="line_association_table_martyrologyline_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "martyrology_id", "martyrologyline_id", name="line_association_table_pkey"
        ),
    )
    op.create_table(
        "prayerline",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("lineno", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="prayerline_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="prayerline_pkey"),
    )
    op.create_index("ix_prayerline_suffix", "prayerline", ["suffix"], unique=False)
    op.create_index("ix_prayerline_rubrics", "prayerline", ["rubrics"], unique=False)
    op.create_index("ix_prayerline_prefix", "prayerline", ["prefix"], unique=False)
    op.create_index("ix_prayerline_id", "prayerline", ["id"], unique=False)
    op.create_index("ix_prayerline_content", "prayerline", ["content"], unique=False)
    op.create_table(
        "hymn_verse_association_table",
        sa.Column("hymn_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("hymnverse_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["hymn_id"], ["hymn.id"], name="hymn_verse_association_table_hymn_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["hymnverse_id"],
            ["hymnverse.id"],
            name="hymn_verse_association_table_hymnverse_id_fkey",
        ),
    )
    op.create_table(
        "line",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["user.id"], name="line_owner_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="line_pkey"),
    )
    op.create_index("ix_line_suffix", "line", ["suffix"], unique=False)
    op.create_index("ix_line_sourcefile", "line", ["sourcefile"], unique=False)
    op.create_index("ix_line_rubrics", "line", ["rubrics"], unique=False)
    op.create_index("ix_line_prefix", "line", ["prefix"], unique=False)
    op.create_index("ix_line_id", "line", ["id"], unique=False)
    op.create_index("ix_line_content", "line", ["content"], unique=False)
    op.create_table(
        "hymn_line_association_table",
        sa.Column("hymnline_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("hymnverse_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["hymnline_id"],
            ["hymnline.id"],
            name="hymn_line_association_table_hymnline_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["hymnverse_id"],
            ["hymnverse.id"],
            name="hymn_line_association_table_hymnverse_id_fkey",
        ),
    )
    op.create_table(
        "bibleverse",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("prefix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("suffix", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("language", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("book", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("aka", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="bibleverse_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="bibleverse_pkey"),
    )
    op.create_index("ix_bibleverse_version", "bibleverse", ["version"], unique=False)
    op.create_index("ix_bibleverse_suffix", "bibleverse", ["suffix"], unique=False)
    op.create_index(
        "ix_bibleverse_sourcefile", "bibleverse", ["sourcefile"], unique=False
    )
    op.create_index("ix_bibleverse_rubrics", "bibleverse", ["rubrics"], unique=False)
    op.create_index("ix_bibleverse_prefix", "bibleverse", ["prefix"], unique=False)
    op.create_index("ix_bibleverse_language", "bibleverse", ["language"], unique=False)
    op.create_index("ix_bibleverse_id", "bibleverse", ["id"], unique=False)
    op.create_index("ix_bibleverse_content", "bibleverse", ["content"], unique=False)
    op.create_index("ix_bibleverse_book", "bibleverse", ["book"], unique=False)
    op.create_index("ix_bibleverse_aka", "bibleverse", ["aka"], unique=False)
    op.create_table(
        "versicle",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("rubrics", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("posture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("sourcefile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["user.id"], name="versicle_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="versicle_pkey"),
    )
    op.create_index("ix_versicle_title", "versicle", ["title"], unique=False)
    op.create_index("ix_versicle_sourcefile", "versicle", ["sourcefile"], unique=False)
    op.create_index("ix_versicle_rubrics", "versicle", ["rubrics"], unique=False)
    op.create_index("ix_versicle_posture", "versicle", ["posture"], unique=False)
    op.create_index("ix_versicle_id", "versicle", ["id"], unique=False)
    op.drop_table("officeassoc")
    op.drop_table("hymnverseassoc")
    op.drop_table("hymnassoc")
    op.drop_index(op.f("ix_officething_version"), table_name="officething")
    op.drop_index(op.f("ix_officething_type_"), table_name="officething")
    op.drop_index(op.f("ix_officething_title"), table_name="officething")
    op.drop_index(op.f("ix_officething_suffix"), table_name="officething")
    op.drop_index(op.f("ix_officething_sourcefile"), table_name="officething")
    op.drop_index(op.f("ix_officething_rubrics"), table_name="officething")
    op.drop_index(op.f("ix_officething_ref"), table_name="officething")
    op.drop_index(op.f("ix_officething_prefix"), table_name="officething")
    op.drop_index(op.f("ix_officething_posture"), table_name="officething")
    op.drop_index(op.f("ix_officething_language"), table_name="officething")
    op.drop_index(op.f("ix_officething_datestr"), table_name="officething")
    op.drop_index(op.f("ix_officething_content"), table_name="officething")
    op.drop_index(op.f("ix_officething_book"), table_name="officething")
    op.drop_index(op.f("ix_officething_aka"), table_name="officething")
    op.drop_table("officething")
    # ### end Alembic commands ###
