"""add owners and make line

Revision ID: a6e51e703eaf
Revises: 4d8a0de0447c
Create Date: 2021-02-25 16:08:05.459008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e51e703eaf'
down_revision = '4d8a0de0447c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse', sa.Column('content', sa.String(), nullable=True))
    op.add_column('verse', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('verse', sa.Column('prefix', sa.String(), nullable=True))
    op.add_column('verse', sa.Column('suffix', sa.String(), nullable=True))
    op.drop_index('ix_verse_title', table_name='verse')
    op.create_index(op.f('ix_verse_content'), 'verse', ['content'], unique=False)
    op.create_index(op.f('ix_verse_prefix'), 'verse', ['prefix'], unique=False)
    op.create_index(op.f('ix_verse_suffix'), 'verse', ['suffix'], unique=False)
    op.create_foreign_key(None, 'verse', 'user', ['owner_id'], ['id'])
    op.drop_column('verse', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'verse', type_='foreignkey')
    op.drop_index(op.f('ix_verse_suffix'), table_name='verse')
    op.drop_index(op.f('ix_verse_prefix'), table_name='verse')
    op.drop_index(op.f('ix_verse_content'), table_name='verse')
    op.create_index('ix_verse_title', 'verse', ['title'], unique=False)
    op.drop_column('verse', 'suffix')
    op.drop_column('verse', 'prefix')
    op.drop_column('verse', 'owner_id')
    op.drop_column('verse', 'content')
    # ### end Alembic commands ###
