"""ownership

Revision ID: aae0a4158650
Revises: 7c7c120a47e9
Create Date: 2021-03-23 16:36:09.182055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae0a4158650'
down_revision = '7c7c120a47e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officething', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'officething', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'officething', type_='foreignkey')
    op.drop_column('officething', 'owner_id')
    # ### end Alembic commands ###
