"""rename col

Revision ID: af308525fd3c
Revises: 6e9d64cbb619
Create Date: 2021-03-03 12:27:29.699632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af308525fd3c'
down_revision = '6e9d64cbb619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_commemoration_at', table_name='commemoration')
    op.drop_column('commemoration', 'at')
    op.drop_index('ix_feast_at', table_name='feast')
    op.drop_column('feast', 'at')
    op.add_column('hymn', sa.Column('type_', sa.String(), nullable=True))
    op.drop_index('ix_hymn_at', table_name='hymn')
    op.create_index(op.f('ix_hymn_type_'), 'hymn', ['type_'], unique=False)
    op.drop_column('hymn', 'at')
    op.drop_index('ix_martyrology_at', table_name='martyrology')
    op.drop_column('martyrology', 'at')
    op.drop_index('ix_verse_at', table_name='verse')
    op.drop_column('verse', 'at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verse', sa.Column('at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_verse_at', 'verse', ['at'], unique=False)
    op.add_column('martyrology', sa.Column('at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_martyrology_at', 'martyrology', ['at'], unique=False)
    op.add_column('hymn', sa.Column('at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_hymn_type_'), table_name='hymn')
    op.create_index('ix_hymn_at', 'hymn', ['at'], unique=False)
    op.drop_column('hymn', 'type_')
    op.add_column('feast', sa.Column('at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_feast_at', 'feast', ['at'], unique=False)
    op.add_column('commemoration', sa.Column('at', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_commemoration_at', 'commemoration', ['at'], unique=False)
    # ### end Alembic commands ###
