"""shot at calendar

Revision ID: bffb6ac4a17d
Revises: db7aaf4bcb6b
Create Date: 2021-02-26 16:37:21.113649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffb6ac4a17d'
down_revision = 'db7aaf4bcb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_date_association_table',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('feast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date_id'], ['datetable.id'], ),
    sa.ForeignKeyConstraint(['feast_id'], ['feast.id'], ),
    sa.PrimaryKeyConstraint('date_id', 'feast_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar_date_association_table')
    # ### end Alembic commands ###
