"""columns need = not :

Revision ID: c9d2cfda23c9
Revises: 74b1aa3c6e1d
Create Date: 2021-03-02 14:54:24.403821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d2cfda23c9'
down_revision = '74b1aa3c6e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hymn', sa.Column('language', sa.String(), nullable=True))
    op.add_column('hymn', sa.Column('version', sa.String(), nullable=True))
    op.create_index(op.f('ix_hymn_language'), 'hymn', ['language'], unique=False)
    op.create_index(op.f('ix_hymn_version'), 'hymn', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hymn_version'), table_name='hymn')
    op.drop_index(op.f('ix_hymn_language'), table_name='hymn')
    op.drop_column('hymn', 'version')
    op.drop_column('hymn', 'language')
    # ### end Alembic commands ###
