"""ref right property

Revision ID: d03fa1b4be98
Revises: a6e51e703eaf
Create Date: 2021-02-25 16:26:08.978836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03fa1b4be98'
down_revision = 'a6e51e703eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
