"""correct ref name

Revision ID: db7aaf4bcb6b
Revises: 2a6db7cd5566
Create Date: 2021-02-26 13:04:30.386690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db7aaf4bcb6b'
down_revision = '2a6db7cd5566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
