"""new models

Revision ID: f4b374f2de80
Revises: 111e9c58cd75
Create Date: 2021-03-19 13:54:13.255209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b374f2de80'
down_revision = '111e9c58cd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibleverse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('aka', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bibleverse_aka'), 'bibleverse', ['aka'], unique=False)
    op.create_index(op.f('ix_bibleverse_book'), 'bibleverse', ['book'], unique=False)
    op.create_index(op.f('ix_bibleverse_content'), 'bibleverse', ['content'], unique=False)
    op.create_index(op.f('ix_bibleverse_id'), 'bibleverse', ['id'], unique=False)
    op.create_index(op.f('ix_bibleverse_language'), 'bibleverse', ['language'], unique=False)
    op.create_index(op.f('ix_bibleverse_prefix'), 'bibleverse', ['prefix'], unique=False)
    op.create_index(op.f('ix_bibleverse_rubrics'), 'bibleverse', ['rubrics'], unique=False)
    op.create_index(op.f('ix_bibleverse_sourcefile'), 'bibleverse', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_bibleverse_suffix'), 'bibleverse', ['suffix'], unique=False)
    op.create_index(op.f('ix_bibleverse_version'), 'bibleverse', ['version'], unique=False)
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('posture', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_id'), 'block', ['id'], unique=False)
    op.create_index(op.f('ix_block_posture'), 'block', ['posture'], unique=False)
    op.create_index(op.f('ix_block_rubrics'), 'block', ['rubrics'], unique=False)
    op.create_index(op.f('ix_block_sourcefile'), 'block', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_block_title'), 'block', ['title'], unique=False)
    op.create_table('line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrics', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('suffix', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('sourcefile', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_content'), 'line', ['content'], unique=False)
    op.create_index(op.f('ix_line_id'), 'line', ['id'], unique=False)
    op.create_index(op.f('ix_line_prefix'), 'line', ['prefix'], unique=False)
    op.create_index(op.f('ix_line_rubrics'), 'line', ['rubrics'], unique=False)
    op.create_index(op.f('ix_line_sourcefile'), 'line', ['sourcefile'], unique=False)
    op.create_index(op.f('ix_line_suffix'), 'line', ['suffix'], unique=False)
    op.create_table('block_line_association_table',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['block.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['line.id'], ),
    sa.PrimaryKeyConstraint('block_id', 'line_id')
    )
    op.drop_index('ix_verse_aka', table_name='verse')
    op.drop_index('ix_verse_book', table_name='verse')
    op.drop_index('ix_verse_content', table_name='verse')
    op.drop_index('ix_verse_id', table_name='verse')
    op.drop_index('ix_verse_language', table_name='verse')
    op.drop_index('ix_verse_prefix', table_name='verse')
    op.drop_index('ix_verse_rubrics', table_name='verse')
    op.drop_index('ix_verse_sourcefile', table_name='verse')
    op.drop_index('ix_verse_suffix', table_name='verse')
    op.drop_index('ix_verse_version', table_name='verse')
    op.drop_table('verse')
    op.add_column('hymn', sa.Column('posture', sa.String(), nullable=True))
    op.create_index(op.f('ix_hymn_posture'), 'hymn', ['posture'], unique=False)
    op.add_column('hymnverse', sa.Column('posture', sa.String(), nullable=True))
    op.create_index(op.f('ix_hymnverse_posture'), 'hymnverse', ['posture'], unique=False)
    op.add_column('martyrology', sa.Column('posture', sa.String(), nullable=True))
    op.add_column('martyrology', sa.Column('read_first', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_martyrology_posture'), 'martyrology', ['posture'], unique=False)
    op.add_column('prayer', sa.Column('posture', sa.String(), nullable=True))
    op.create_index(op.f('ix_prayer_posture'), 'prayer', ['posture'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prayer_posture'), table_name='prayer')
    op.drop_column('prayer', 'posture')
    op.drop_index(op.f('ix_martyrology_posture'), table_name='martyrology')
    op.drop_column('martyrology', 'read_first')
    op.drop_column('martyrology', 'posture')
    op.drop_index(op.f('ix_hymnverse_posture'), table_name='hymnverse')
    op.drop_column('hymnverse', 'posture')
    op.drop_index(op.f('ix_hymn_posture'), table_name='hymn')
    op.drop_column('hymn', 'posture')
    op.create_table('verse',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rubrics', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('book', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prefix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('suffix', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('aka', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sourcefile', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='verse_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='verse_pkey')
    )
    op.create_index('ix_verse_version', 'verse', ['version'], unique=False)
    op.create_index('ix_verse_suffix', 'verse', ['suffix'], unique=False)
    op.create_index('ix_verse_sourcefile', 'verse', ['sourcefile'], unique=False)
    op.create_index('ix_verse_rubrics', 'verse', ['rubrics'], unique=False)
    op.create_index('ix_verse_prefix', 'verse', ['prefix'], unique=False)
    op.create_index('ix_verse_language', 'verse', ['language'], unique=False)
    op.create_index('ix_verse_id', 'verse', ['id'], unique=False)
    op.create_index('ix_verse_content', 'verse', ['content'], unique=False)
    op.create_index('ix_verse_book', 'verse', ['book'], unique=False)
    op.create_index('ix_verse_aka', 'verse', ['aka'], unique=False)
    op.drop_table('block_line_association_table')
    op.drop_index(op.f('ix_line_suffix'), table_name='line')
    op.drop_index(op.f('ix_line_sourcefile'), table_name='line')
    op.drop_index(op.f('ix_line_rubrics'), table_name='line')
    op.drop_index(op.f('ix_line_prefix'), table_name='line')
    op.drop_index(op.f('ix_line_id'), table_name='line')
    op.drop_index(op.f('ix_line_content'), table_name='line')
    op.drop_table('line')
    op.drop_index(op.f('ix_block_title'), table_name='block')
    op.drop_index(op.f('ix_block_sourcefile'), table_name='block')
    op.drop_index(op.f('ix_block_rubrics'), table_name='block')
    op.drop_index(op.f('ix_block_posture'), table_name='block')
    op.drop_index(op.f('ix_block_id'), table_name='block')
    op.drop_table('block')
    op.drop_index(op.f('ix_bibleverse_version'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_suffix'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_sourcefile'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_rubrics'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_prefix'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_language'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_id'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_content'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_book'), table_name='bibleverse')
    op.drop_index(op.f('ix_bibleverse_aka'), table_name='bibleverse')
    op.drop_table('bibleverse')
    # ### end Alembic commands ###
