on:
  push:
    branches: production
  pull_request:
  workflow_dispatch:

name: Build docker images and push to repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up git repo
        uses: actions/checkout@v2

      - name: Get .env file from secret
        run: |
          echo "${{ secrets.DOCKER_ENV }}" > .env
          head -n 1 .env
          pwd
      
      - name: Run build script
        run: |
          TAG=prod FRONTEND_ENV=production sh ./scripts/build-push.sh

      - name: Make stack file
        run: |
          DOMAIN=2e0byo.co.uk \
          TRAEFIK_TAG=2e0byo.co.uk \
          STACK_NAME=2e0byo-co-uk \
          TAG=prod \
          docker-compose \
          -f docker-compose.yml \
          config > docker-stack.yml
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
              HostName ${{ secrets.SSH_HOST }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/deploy.key
              StrickHostKeyChecking no
          END
          scp docker-stack.yml deploy:
         

      - name: Deploy to swarm
        run: |
          ssh deploy 'docker-auto-labels 2e0byo-co-uk && docker stack deploy -c docker-stack.yml 2e0byo-co-uk'
