on:
  push:
    branches: master
  pull_request:
  workflow_dispatch:

name: Build docker images and push to repo

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Set up git repo
        uses: actions/checkout@v2

      - name: Get .env file from secret
        run: |
          echo "${{ secrets.DOCKER_ENV }}" > .env
          head -n 1 .env
          pwd
      
      - name: Run build script
        run: |
          TAG=stag FRONTEND_ENV=staging sh ./scripts/build-push.sh
        
