on:
  push:
  pull_request:
  workflow_dispatch:

name: Run tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up git repo
        uses: actions/checkout@v2

      - name: Get .env file from secret
        run: |
          echo "${{ secrets.DOCKER_ENV }}" > .env

      - name: Set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
              HostName ${{ secrets.SSH_HOST }}
              User ${{ secrets.SSH_USER }}
              IdentityFile ~/.ssh/deploy.key
              StrictHostKeyChecking no
          END

      - name: test copy .env
        run: |
          scp .env "deploy:"

      # - name: Test
      #   run: bash ./scripts/test.sh
      - name: setup docker-stack.yml
        run: |
          DOMAIN=backend \
          SMTP_HOST="" \
          TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL=false \
          INSTALL_DEV=true \
          docker-compose \
          -f docker-compose.yml \
          config > docker-stack.yml

      - name: save yml
        uses: actions/upload-artifact@v1.0.0
        with:
          name: docker-stack.yml
          path: docker-stack.yml
          
      - name: build
        run: docker-compose -f docker-stack.yml build
      - name: down
        run: docker-compose -f docker-stack.yml down -v
      - name: up
        run: docker-compose -f docker-stack.yml up -d
      - name: exec
        run: docker-compose -f docker-stack.yml exec -T backend bash /app/tests-start.sh "$@"
      - name: remove
        run: docker-compose -f docker-stack.yml down -v --remove-orphans
