on:
  push:
  pull_request:
  workflow_dispatch:

name: Run tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2

      - name: Get .env file from secret
        run: |
          echo "${{ secrets.DOCKER_ENV }}" > .env

      - name: Test
        run: bash ./scripts/test.sh
